[package]
name        = "cab"
description = "A reproducible derivation file composer"
version     = "0.0.1"
edition     = "2024"

[dependencies]
cab-syntax.path     = "../cab-syntax"
clap-stdin          = "0.5.1"
clap-verbosity-flag = "3.0.2"
env_logger          = "0.11.3"
log                 = "0.4.21"
thiserror           = "2.0.11"

[dependencies.clap]
version = "4.5.4"
features = [ "derive" ]

[dependencies.tokio]
version = "1.37.0"
features = [ "full" ]

[dependencies.yansi]
version = "1.0.1"
features = [ "detect-env", "detect-tty", "hyperlink" ]

[dependencies.miette]
version  = "7.4.0"
features = [ "fancy" ]